### PR TITLE
forced leap snap to use getOfflineSignerOnlyAmino as other signing methods cause issues

### PR DESCRIPTION
**Pull request by TrevorJTClarke**
## Description

This PR ...

## Checklist

- [x] I have made sure the upstream branch for this PR is correct
- [x] I have made sure this PR is ready to merge
- [x] I have made sure that I have assigned reviewers related to this project

## Changes

- [x] Changed the leap snap method to only support `getOfflineSignerOnlyAmino`

## Testing

- Sign any TX with leap metamask snap

### CODE REVIEW

**Comment by TrevorJTClarke** [comment]
NOTE: Ive got nextjs example changes as well @codingki - however i wasn't sure if you'd like stargaze specific TX within the example UIs. LMK if you want added

**Comment by codingki** [comment]
yes, you can include stargate specific tx in the example @TrevorJTClarke

**Comment by TrevorJTClarke** [comment]
I've added example for how to sign a TX inside nextjs example, here's some screenshots of what that looks like:

Screenshot 2024-04-25 at 11 07 35 AM
Screenshot 2024-04-25 at 11 11 06 AM
Screenshot 2024-04-25 at 11 10 58 AM
Screenshot 2024-04-25 at 11 10 43 AM
Screenshot 2024-04-25 at 11 10 32 AM
Screenshot 2024-04-25 at 11 07 46 AM
Screenshot 2024-04-25 at 11 07 41 AM

**Comment by codingki** [comment]
@TrevorJTClarke Tested your tx test, it works. Please remove the example updates in the PR so I can merge and release

**Pull request merged**
