### PR TITLE
feat: vectis integration

### PR DESCRIPTION
**Pull request by j0nl1**
## Description

This PR includes support for vectis extension.

Vectis by NYMLAB is a smart contract wallet infrastructure that allows user to interact with dApps on the blockchain with the same amount of autonomy of a classic non-custodial solution. Vectis extension allows to interact with smart contract wallets as it was an EOA, from a dApp perspective there is not difference. 

More information about [vectis](https://github.com/nymlab/vectis).

## Checklist

- [x] I have made sure the upstream branch for this PR is correct
- [x] I have made sure this PR is ready to merge
- [x] I have made sure that I have assigned reviewers related to this project

## Links
- [Vectis Website](https://testnet-app.vectis.space)

## Notes
- Issue reference for integration: https://github.com/strangelove-ventures/graz/issues/98

### CODE REVIEW

**Comment by codingki** [comment]
@j0nl1 I create a PR to your repo for adding vectis connect wallet button to example and templates.
here: https://github.com/nymlab/graz/pull/1

**Comment by j0nl1** [comment]
@codingki  Thank you, it's merged!

**Comment by codingki** [comment]
@j0nl1 Sorry there was a typo, please merge this first and I'll test https://github.com/nymlab/graz/pull/2

**Comment by codingki** [comment]
@j0nl1 is this the download link https://chrome.google.com/webstore/detail/vectis/cgkaddoglojnmfiblgmlinfaijcdpfjm/ ?

**Comment by j0nl1** [comment]
@codingki yes, it is. After testing the integration, getKey method was giving a infinity loop because vectis global provider was being mutated. Instead of mutate global provider with object.assign, I decided to return a new object.

**Comment by codingki** [comment]
Perfect @j0nl1 tested and works now

**Pull request merged**
