### PR TITLE
Change juno testnet chain id

### PR DESCRIPTION
**Pull request by findolor**
This PR changes juno uni testnet chain id to be uni-5.

### CODE REVIEW

**Review by codingki — APPROVED** [review]

**Comment by findolor** [comment]
@codingki Would this be included in the npm package after merging or you have to upload another version for it?

I use the juno testnet regularly so if it's included that would be awesome.

**Comment by codingki** [comment]
@findolor we need to upload it to npm. it will be included in 0.0.28+ version

**Comment by findolor** [comment]
@codingki Sounds good, any dates on that?

**Comment by codingki** [comment]
we don't have an exact date, I'll make sure it will be released this week asap

**Comment by codingki** [comment]
@findolor v0.0.28 is released https://github.com/strangelove-ventures/graz/releases/tag/v0.0.28

**Comment by findolor** [comment]
@codingki Thanks a lot for the fast release 🚀

**Pull request merged**
