### PR TITLE
Use standard clients for queries

### PR DESCRIPTION
**Pull request by bigs**
## Description

This PR relaxes the smart contract query hooks requirements from a signing CosmWasm client to a standard CosmWasm client. This makes it possible to use the hooks when an application has not connected a wallet or otherwise created a signing client.

## Checklist

- [x] I have made sure the upstream branch for this PR is correct
- [x] I have made sure this PR is ready to merge
- [x] I have made sure that I have assigned reviewers related to this project

## Changes

- [x] Changed destructuring of the graz store to pull out the standard clients object rather than the signing clients object and subsequently use it to execute CosmWasm queries when a CosmWasm client is present.

## Testing

- Create a sample application that instantiates clients via `useClients`
- Query a smart contract on the target chain with one of the useQuerySmart or useQueryRaw hooks
- Verify that a result was returned without need for a signing client.

### CODE REVIEW

**Comment by codingki** [comment]
@bigs I think we should remove `address` from react query  hook options (`enabled`) because if it's not connected this hook won't run
https://github.com/strangelove-ventures/graz/blob/dev/packages/graz/src/hooks/methods.ts#L269
https://github.com/strangelove-ventures/graz/blob/dev/packages/graz/src/hooks/methods.ts#L292

**Comment by bigs** [comment]
> @bigs I think we should remove `address` from react query hook options (`enabled`) because if it's not connected this hook won't run https://github.com/strangelove-ventures/graz/blob/dev/packages/graz/src/hooks/methods.ts#L269 https://github.com/strangelove-ventures/graz/blob/dev/packages/graz/src/hooks/methods.ts#L292

I'm not 100% sure I'm reading you right, but the reason we made `address` optional in the hook arguments, but required in the "action" (and present in the `enabled` flag) was to account for cases where the contract address was not known at first component load. A simple example of this from a product we are building is a contract representing a community that has a reference to the contract address of a corresponding membership/seat/token contract. So we have dependent queries—first we must query the community contract and get the contract address for the membership contract, at which point we can query the membership contract for information.

Does that address your concern? I may be misunderstanding!

**Comment by codingki** [comment]
Oh yea I got your point. My mistake I thought that `address` coming from user wallet

**Review by codingki — APPROVED** [review]

**Comment by bigs** [comment]
Awesome, thank you! :)

**Comment by codingki** [comment]
Released @bigs https://github.com/strangelove-ventures/graz/releases/tag/v0.0.33 🚀

**Pull request merged**
